{
  "_id":"_design/metadata",
  "_rev":"3-3d8c346a40f5a0db1fb8460555b6cf09",
  "lists":{
    "collate":"#",
    "distinct_keys":"#"
  },
  "rewrites":[
    {
      "from":"/makeModels/",
      "to":"/_list/collate/make_models"
    },
    {
      "from":"/makeModels/:make/",
      "query":{
        "key":":make"
      },
      "to":"/_list/collate/make_models"
    },
    {
      "from":"/makes/",
      "query":{
        "group":"true"
      },
      "to":"/_list/distinct_keys/makes"
    },
    {
      "from":"/engines/:mmid",
      "query":{
        "key":":mmid"
      },
      "to":"/_view/engines/"
    }
  ],
  "views":{
    "doc_types":{
      "map":"#",
      "reduce":"#"
    },
    "engines":{
      "map":"#"
    },
    "make_model_ids":{
      "map":"#"
    },
    "make_models":{
      "map":"#"
    },
    "makes":{
      "map":"#",
      "reduce":"#"
    }
  }
}